plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

#storybook requires nodeLinker for now, 6.4 builds are broken
nodeLinker: 'node-modules'
#pnpMode: loose

yarnPath: .yarn/releases/yarn-3.2.0-rc.12.cjs
