name: Build & Deploy Storybook
on:
  push:
    branches:
      - feature/sb_workflow_test
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - name: Deploy Storybook to GH Pages
        run: npm run deploy:sb -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
