name: Build & Deploy Storybook
on:
  push:
    branches:
      - feature/sb_workflow_test
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-node@v3
        with:
          cmd: deploy:sb -- --ci
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
