name: Build & Deploy Storybook
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: deploy:sb -- --ci
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
